### ISSUE TITLE
WARNING: pytg2.receiver:Received message could not be parsed.

### ISSUE THREAD

**Issue by Mugen4** [luckydonald/pytg2#1]
Hi,

I just tried the new pytg2 0.4 and  I get this error with dump.py

```
root@raspberrypi:/var/alarma/pytg2/examples# python dump.py

WARNING:pytg2.receiver:Received message could not be parsed.
Message:>User user online (was online [2015/05/16 18:21:55])<
Traceback (most recent call last):
  File "build/bdist.linux-armv7l/egg/pytg2/receiver.py", line 166, in _add_message
    json_dict = json.loads(text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
WARNING:pytg2.receiver:Received message could not be parsed.
Message:>[18:16]  !_user >>> gff<
Traceback (most recent call last):
  File "build/bdist.linux-armv7l/egg/pytg2/receiver.py", line 166, in _add_message
    json_dict = json.loads(text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 1 column 4 (char 3)

```

It receive data from telegram-cli but can't parse or decode, I think I miss a python pack or something. This is my python package list:

```
# pip list
argparse (1.2.1)
characteristic (0.1.0)
chardet (2.3.0)
colorama (0.3.3)
deluge (1.3.10)
DictObject (0.1.1)
dnspython (1.12.0)
future (0.14.3)
html5lib (0.999)
mcpi (0.1.1)
ndg-httpsclient (0.3.2)
numpy (1.8.2)
PAM (0.4.2)
pexpect (3.3)
picamera (1.10)
pifacecommon (4.1.2)
pifacedigitalio (3.0.4)
pip (1.5.6)
pyasn1 (0.1.7)
pyasn1-modules (0.0.5)
pycrypto (2.6.1)
pygobject (3.14.0)
pyOpenSSL (0.13.1)
pyserial (2.6)
pytg2 (0.4.0)
python-libtorrent (0.16.18)
pyxdg (0.25)
requests (2.4.3)
RPi.GPIO (0.5.11)
service-identity (1.0.0)
setuptools (5.5.1)
simplejson (3.6.5)
six (1.9.0)
Twisted-Core (14.0.2)
Twisted-Web (14.0.2)
urllib3 (1.10.4)
wheel (0.24.0)
wicd (1.7.2.4)
wsgiref (0.1.2)
zope.interface (4.1.1)
```

Thanks

**Comment by luckydonald** [comment]
Did you start the `telegram-cli` by yourself?
It looks like you forgot the `--json` flag.

**Comment by luckydonald** [comment]
I updated the README file, this was unclear. (f4e0f6c)

**Comment by Mugen4** [comment]
Yeah, the problem was the --json flag

Thanks!
